gemfile: Gemfile

PreCommit:
  ALL:
    problem_on_unmodified_line: ignore
  RuboCop:
    enabled: true
    required_executable: bundle
    command: ["bundle", "exec", "rubocop"]

CommitMsg:
  ALL:
    enabled: false
