branches:
  only:
    - main
dist: jammy
language: ruby
jobs:
  include:
    - name: lint
      language: ruby
      rvm: 3.3
      install: bin/setup
      script: bin/rake rubocop
    - name: test
      language: ruby
      rvm:
        - 3.1
        - 3.2
        - 3.3
      install: bin/setup
      script: bin/rake appraisal rspec
